### ISSUE TITLE
Insane simplicity but SDL input doesnt work

### ISSUE THREAD

**Issue by rt974** [sansajn/ogre-linux-starter#1]
Hey, 

i really liked this tutorial, but somehow SDL events are not fired, this is really weird i have to close the window with the process manager or when running from console, ctrl+c

never had this type of problem with ogre before.

`	if (evt.keysym.sym == SDLK_ESCAPE)
`

Dont know why SDL events are ignored.

**Comment by sansajn** [comment]
thank you for issue report, I can confirm it is happening

**Comment by sansajn** [comment]
> Hey,
> 
> i really liked this tutorial, but somehow SDL events are not fired, this is really weird i have to close the window with the process manager or when running from console, ctrl+c
> 
> never had this type of problem with ogre before.
> 
> ` if (evt.keysym.sym == SDLK_ESCAPE) `
> 
> Dont know why SDL events are ignored.

**Comment by sansajn** [comment]
Hello, I've found that default repository package is broken in Ubuntu 20.04 LTS and the only way to fix it is to build your own OGRE library.
